### ISSUE TITLE
Syrinscape non-online player not supported?

### ISSUE THREAD

**Issue by thorr18** [Moroverse/syrinscape_bridge#5]
I love syrinscape_bridge. It works great. It seems like it wasn't made to support the other syrinscape players though. Can you confirm?

**Comment by danielmoro** [comment]
Hi,
Unfortunately you are right. Non-online players cannot benefit from it. I would like to have some remedy for them also, but didn't find any viable solution for that yet 😔 .

**Comment by ksignorini** [comment]
I think it's more important to look at it as part of the Syrinscape Online (beta) Player package. It has a different purpose than the standalone players.

The Online (beta) is for distributed sound playing. The standalone ones (Fantasy, Sci-Fi, BoardGame) are for in-person-running-on-one-computer-like-a-stereo-system playing.
